language: node_js
node_js: node
script:
- npm run test:lint
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then polymer test --skip-plugin local; fi'
- 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then polymer test --skip-plugin sauce; fi'
env:
  global:
    - SAUCE_USERNAME: Desire2Learn
    #SAUCE_ACCESS_KEY
    - secure: Uj0dcZxTrBnUqU3g7uYXgEtJNSy1otnaP0ND96Sxus5lvjwhZ6z3SKHRwgxzJ8pIXI41Enx1LeLJIROSreXbo6rv4iw9K7y233yQ0jo5d7WxU+8ZyfAWpZ7IC3zT2i3mfpkcR9Hv53CV/eLwLWdEKwGf8w1aqPUApd+/USMsbT2oIbPIImQrC8vihJW1k0W2Gj/aww9h7NzEbxycI9Ke752JStfHrsOojqDekOu3/6ejwWaezWypky9533/eTyiBjVZINbi+FHTjYNl0kekZS784405qbV5XsPPRF4FtJBNZ22R7rO0hNTSFb68f1fjZ66WS4xlFcU821sXoxRMubhN8rlfUHmf/ZN22DAm0Rr69dgRi5CQ8PPqlXsxceEWkqOnOtoRvnoefFkxLX9yWrgZnU71fbPBeenvzTTtK5CwiuzI3crps97R99KsyLBSibAaULABseIy0WEoglBUPZ/bj/gphfb5aCH2qIIPIqHiJ+tbwSX1HOJVIFc1Z0IqWxspQaKAPGYHGgI26wV0w+fbgk+tDUkNewb6uim9SpXkPCRMl2/y2AgnugqD04vZAVV/xJKtW/urcFBinNUjsxrUnpuLlIZz2McN0M6wqBoQVybAfAPCy+9VRgvmIxXntfcfluHXVOR5/wNrPZNNblMTSM8BCGBCDljJm1lxF1Yo=
