language: node_js
node_js: node
script:
- npm run lint
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=tooltip
  - secure: arpN5ttvh5qKysySTUyLem2nV4zKXlhUtEiG7JSLTMHVFuxVtVRba016RHvTIHuX7rGoI1KnrVsiGBcV/bTla3+8C/WG+yJloJTyl5TtabGcUWct8vA8EZV5aiHlvowMydyzWAkAoybc515VIvkBtezREvSHW7h33Y1lV6Fsmtga6s3VQnTqSiZX0QRfXlSvQvAWMH2vmMAcemdG3OoovlgZ5twmKxSCXM7KnzUui3+ZReZWUh9ZC7PZVQmfzcVDg1Nqo+d7BSAp8vbsIc2c9B/v/o16bhFnVSnlOagZ2k/raL8gh+B4WZnI5i0N+daXIg5lSOXl7RGQhL8oovTSS+Y9ypelAVMQAAIsxGBmAK2Dm52Rbx2mNXbobuOnMXQhQlw9N07LroSBTVAtfME5832Ondrn5coEDRFlRno7aBdFZHMXBazRNPogQNKv3jeDjWuNA2xVOwF63K5xrlDUmT78ckoxn8OB4CFgttzAPgjJYEsa6JmTrkcTYC8yCWIwJ8Flq11AdU3KWBstFty7ex+0MGeWpdo9q/EWjLwE9AXEz6g3m0Hj40omtz9tNJlInchEZRvuqCI6xSEXK0veTNrLWaWEtWcsscajqJ5A0+9gEZR+zhRWZcgImnMkTxGLETdxicA6UjkxbHc2Xn8LJoRvT8Cx4/qngd6wb/lhFOM=
